services:
  aiti_guru-backend:
    build:
      context: ..
      dockerfile: /deployments/app/Dockerfile
    container_name: aiti_guru-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "../app:/app/app"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    container_name: aiti_guru-postgres
    image: postgres:14.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "../pgdata:/var/lib/postgresql/data"